### ISSUE TITLE
폰트 파일을 업로드해서 사용하는 기능 추가

### ISSUE THREAD

**Issue by ghost** [things-factory/font-base#4]
폰트 파일을 서버에 업로드해서 사용할 수 있도록 기능을 추가

**Comment by ghost** [comment]
파일을 직접 서버에 넣어주는 것 외에 attachment 모듈을 활용하는 방안도 고려

**Comment by ghost** [comment]
폰트 파일을 바로 업로드할 수 있도록 ui추가

**Comment by ghost** [comment]
폰트 파일 업로드 기능은 첨부 모듈의 기능과 완전히 겹치므로 필요한 기능을 임포트해서 사용
폰트 모듈 자체는 첨부 모듈과 분리하여 사용 가능하므로, attachment 모듈 존재 여부에 따라 파일 업로드 UI 표시 결정

- [x] 파일 선택하여 업로드
- [x] 드래그&드랍으로 업로드
- [x] 형식 검사 여부? (.ttf, .woff, .woff2 ...)
- [x] 폰트 삭제 시 파일도 함께 삭제 ~~(무조건 삭제한다면 폰트 파일 URL을 업데이트한 후 삭제하는 방법으로 쓸모가 없어지므로, 폰트 파일을 삭제할 지 묻는 절차 필요)~~ 현재 폰트 파일을 수정할 방법은 없음

##### 그 외
- [x] 리 파일 첨부해놓고 URL도 쓰면 폰트 가져올 때 우선순위?
   - 파일 첨부하면 URL을 파일명으로 덮는 것으로 처리
- [x] 파일 첨부하면 어떤 파일이 첨부됐는지 보여주는 기능?
- [x] 파일 첨부 클리어 기능?
   - 카드를 다시 뒤집으면 클리어되도록 처리

**Comment by lllleeee** [comment]
폰트 업로드 선택 시 attachment-ui 팝업을 띄워주는 방법으로 진행

**Comment by ghost** [comment]
- 파일을 직접 선택해 업로드하는 경우
   1. 파일 첨부 후 submit
   1. create-font 이벤트에서 파일 첨부 여부 확인
   1. 파일이 첨부되어 있으면 먼저 create-attachment 작업을 수행
   1. DB 업데이트 이후 결과의 URL값을 폰트에 넣고 폰트 생성
- 드래그&드랍으로 업로드한 경우
   1. 형식 검사 (.ttf, .woff, .woff2, .eof, .svg 등)
   1. 폰트 명은 파일명을 그대로 사용
   1. create-attachment, create-font 작업을 순차적으로 수행

**Comment by ghost** [comment]
폰트 파일 업로드 후 첨부 파일 페이지도 refresh 해야 함.. 중요도 낮음

**Comment by ghost** [comment]
프로세스 순서 때문에 font 명 중복으로 폰트를 생성하지 못한 경우에도 attachment는 생성되어 있음
